version: '3'
services:
  frontend:
    build: ./fronted
    networks:
      custom_net:
        ipv4_address: 172.11.0.2
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    networks:
      custom_net:
        ipv4_address: 172.11.0.3
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    build: ./redis
    networks:
      custom_net:
        ipv4_address: 172.11.0.4
    restart: unless-stopped


networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/16